name: Deploy with Git Safe Directory and Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SECRET_KEY }}  # 정확한 Secret 이름 사용

    - name: Add SSH key to known hosts
      run: ssh-keyscan -p 40022 182.217.20.249 >> ~/.ssh/known_hosts

    - name: List SSH keys (Debugging)
      run: ssh-add -L

    - name: Test SSH Connection
      run: |
        ssh -v -o StrictHostKeyChecking=no -p 40022 aceit@182.217.20.249 'echo "SSH Connection Successful"'

    - name: Deploy with Git Safe Directory and Docker Compose
      run: |
        ssh -v -o StrictHostKeyChecking=no -p 40022 aceit@182.217.20.249 << 'EOF'
          set -e  # 오류 발생 시 스크립트 중단

          # Frontend 배포
          cd /home/test1/ace_it_project_frontend/aceit  # Frontend 경로로 이동
          git config --global --add safe.directory /home/test1/ace_it_project_frontend  # 안전한 디렉토리로 등록
          git fetch origin
          git reset --hard origin/main  # 로컬을 origin/main과 동기화
          docker-compose down
          docker-compose up -d --build

          # Backend 배포
          cd /home/test1/ace_it_project_backend/aceit  # Backend 경로로 이동
          git config --global --add safe.directory /home/test1/ace_it_project_backend  # 안전한 디렉토리로 등록
          git fetch origin
          git reset --hard origin/main  # 로컬을 origin/main과 동기화
          docker-compose down
          docker-compose up -d --build
        EOF
      env:
        DOCKER_HOST: "ssh://aceit@182.217.20.249"
