name: Deploy with Git Safe Directory and Docker Compose

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SECRET_KEY }}  # 정확한 Secret 이름 사용

    - name: Add SSH key to known hosts
      run: ssh-keyscan -p 40022 182.217.20.249 >> ~/.ssh/known_hosts

    - name: List SSH keys (Debugging)
      run: ssh-add -L

    - name: Test SSH Connection
      run: |
        ssh -v -o StrictHostKeyChecking=no -p 40022 aceit@182.217.20.249 'echo "SSH Connection Successful"'

    - name: Deploy with Git Safe Directory and Docker Compose
      run: |
        ssh -v -o StrictHostKeyChecking=no -p 40022 aceit@182.217.20.249 << 'EOF'
          set -e  # 오류 발생 시 스크립트 중단

          # Git Safe Directory 설정
          git config --global --add safe.directory /home/ace-it  # 전체 프로젝트 디렉토리를 안전한 디렉토리로 등록

          # 프론트엔드 디렉터리로 이동하여 Git 동기화 및 Docker Compose 실행
          cd /home/ace-it/frontend/aceit
          git fetch origin
          git reset --hard origin/main

          # 백엔드 디렉터리로 이동하여 Git 동기화 및 Docker Compose 실행
          cd /home/ace-it/backend/aceit
          git fetch origin
          git reset --hard origin/main

          # 프로젝트 루트에서 Docker Compose 실행
          cd /home/ace-it  # 프로젝트 루트 디렉토리로 이동
          docker-compose down
          docker-compose up -d --build
        EOF
      env:
        DOCKER_HOST: "ssh://aceit@182.217.20.249"
